version: '3.5'
services:
  ngnix:
    container_name: nginx
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    depends_on:
    - wordpress
    build: ./requirements/nginx/
    env_file: .env
    ports:
    - "443:443"
    restart: on-failure

  wordpress:
    container_name: wordpress
    env_file: .env
    volumes:
    - wordpress:/var/www/wordpress
    networks:
    - inception
    build: ./requirements/wordpress
    depends_on:
    - mariadb
    restart: on-failure
    expose: 
    - "9000"

  mariadb:
    container_name: mariadb
    networks:
    - inception
    build: ./requirements/mariadb/
    env_file: .env
    volumes:
    - mariadb:/var/lib/mysql
    restart: unless-stopped
    expose:
    - "3306"

networks:
  inception :
    driver : bridge


volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/Users/zak/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none' 
      o: 'bind'
      device: '/Users/zak/data/mariadb'